--- 
before_install: 
  - "wget http://apache.claz.org/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"
  - "tar zxvf apache-maven-3.3.9-bin.tar.gz"
  - "chmod +x apache-maven-3.3.9/bin/mvn"
  - "export M2_HOME=$PWD/apache-maven-3.3.9"
  - "export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}"
  - "hash -r"
  - "chmod +x apache-maven-3.3.9/bin/mvnw"

cache: 
  directories: 
    - $HOME/.m2
jdk: 
  - oraclejdk8
language: java
notifications: 
  email: 
    - prasupassion@gmail.com
script: "mvn clean install"
matrix:
  include:
  - jdk: oraclejdk8
    script: mvn install
    after_success: mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true
sudo: false